server:
  port: 5000
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: p3spvRimuASb30XeVVGPORwYDZeZtgD3

            client-secret: FB00FYsKwYXlnyrwkZidvowVuJL2DbGlohZ9OV_POyVrSSm83ShPZO3PFRuOIhOF

            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-cd4uq5z8.us.auth0.com/