package com.gonsalves.TimeManagementSystem.repository.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.ArrayList;
import java.util.List;
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "TimeManagementWebApp-Projects")
public class ProjectRecord {
    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "project_id")
    private String projectId;
    @DynamoDBRangeKey(attributeName = "owner_username")
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "owner_username-project_name-index")
    private String username;
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "owner_username-project_name-index")
    @DynamoDBAttribute(attributeName = "project_name")
    private String projectName;
    @DynamoDBAttribute(attributeName = "tasks")
    private List<TaskRecord> taskRecords;
    @DynamoDBAttribute(attributeName = "completion_percent")
    private int completionPercent;
    @DynamoDBAttribute(attributeName = "total_time_contributed")
    private String totalTimeContributed;
    @DynamoDBAutoGeneratedTimestamp
    @DynamoDBAttribute
    private String creation_time;


}